/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":skrapers"))
    api(libs.com.xenomachina.kotlin.argparser)
    api(libs.com.github.ajalt.mordant)
    api(libs.me.tongfei.progressbar)
    api(libs.io.ktor.ktor.client.cio.jvm)
    api(libs.com.fasterxml.jackson.module.jackson.module.kotlin.x1)
    api(libs.com.fasterxml.jackson.dataformat.jackson.dataformat.csv)
    api(libs.com.fasterxml.jackson.dataformat.jackson.dataformat.xml)
    api(libs.com.fasterxml.jackson.dataformat.jackson.dataformat.yaml)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jdk8.x1)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310.x1)
    api(libs.org.slf4j.slf4j.simple)
}

description = "cli"
