/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":skrapers"))
    api(libs.org.springframework.boot.spring.boot.starter.webflux)
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.org.telegram.telegrambots.spring.boot.starter)
    api(libs.com.fasterxml.jackson.module.jackson.module.kotlin)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jdk8)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310)
    api(libs.org.jetbrains.kotlinx.kotlinx.coroutines.reactor)
    api(libs.org.zalando.logbook.spring.boot.webflux.autoconfigure)
    api(libs.io.ktor.ktor.client.cio.jvm)
    api(libs.org.springframework.boot.spring.boot.configuration.processor)
}

description = "telegram-bot"
