/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    api(libs.org.jetbrains.kotlinx.kotlinx.coroutines.core)
    api(libs.org.jsoup.jsoup)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.com.squareup.okhttp3.okhttp)
    api(libs.org.springframework.spring.webflux)
    api(libs.org.jetbrains.kotlinx.kotlinx.coroutines.reactor.x1)
    api(libs.io.ktor.ktor.client.core.jvm)
    testImplementation(libs.org.jetbrains.kotlin.kotlin.test.junit5)
    testImplementation(libs.org.jetbrains.kotlinx.kotlinx.coroutines.test)
    testImplementation(libs.org.slf4j.slf4j.simple)
    testImplementation(libs.ch.qos.logback.logback.classic)
    testImplementation(libs.io.ktor.ktor.client.cio.jvm)
    testImplementation(libs.io.projectreactor.netty.reactor.netty)
    testImplementation(libs.com.fasterxml.jackson.datatype.jackson.datatype.jdk8.x1)
    testImplementation(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310.x1)
}

description = "skrapers"
